[package]
name = "midi"
version = "0.1.0"
authors = ["Gabriel PoÃ§a <gabrielpoca@gmail.com>"]
edition = "2018"

[dependencies]
midir = "0.5.0"
tui = "0.5"
termion = "1.5"
rand = "0.6.5"
crossbeam-channel = "0.3.8"
